### ISSUE TITLE
Memory Size Question

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera-labs/serverless-iiif#39]
Hello,

Is there any sort of hard minimum for the memory size set for the lambda function? I see it is set at 3008 MB. After some brief testing, I noticed that for the images I was using each request was using between 150-300 MB memory. Of course, different image size would create different conditions, but just wondering if there's any other reason that I'm not seeing it would need to be that high, it if our image set was only necessitating that amount.

Thanks (and hopefully last time I bug you :wink:)

Joseph Anderson

**Comment by mbklein** [comment]
Yes, you can absolutely fine tune the memory size of the deployed function, and I definitely recommend doing so. As long as you're confident that your test cases are a good representative sample, you should have no trouble at all.

**Comment by fitnycdigitalinitiatives** [comment]
Thanks!
