### ISSUE TITLE
RENAME: Update CONTRIBUTING.md to match the maintenance template

### ISSUE THREAD

**Issue by kelynch** [samvera-labs/serverless-iiif#48]
The [maintenance template for CONTRIBUTING.md](https://raw.githubusercontent.com/samvera/maintenance/main/templates/CONTRIBUTING.md) is used by all Samvera repos.  Replace the current version with the updated maintenance template version.

**Comment by mbklein** [comment]
Thanks, @kelynch. I think using the Samvera document as a base and adding in the serverless-iiif specific stuff is probably the best approach. I'll keep this open and try to find time to do it.

**Comment by mbklein** [comment]
Closed by #79
