### ISSUE TITLE
Unable to set UseCacheBucket as false

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera-labs/serverless-iiif#56]
When I try to deploy with UseCacheBucket as false, it throws this error and fails:

"Change set creation failed. Reason: Template format error: Unresolved resource dependencies [CacheBucket] in the Resources block of the template"

**Comment by mbklein** [comment]
Thanks for reporting this. Keeping a single SAM template for both caching and non-caching deployments has been tricky and I suspect the end result may be two separate SAM applications with separate templates. I'll look into this as soon as I can, though, and see what I can do.

**Comment by fitnycdigitalinitiatives** [comment]
Thanks, I'm still in the testing phase, so I'm still figuring things.

Just to clarify, this caching only occurs when returning responses that are larger than 6mb. I don't really foresee our usecase ever returning things that large. 

On the other hand, what I would like to do is put the entire api endpoint behind cloudfront so that _all_ the images responses are cached, so it only need to process a whole image once. Does that make sense? Or is the api gateway already doing that?

**Comment by fitnycdigitalinitiatives** [comment]
Ok, I see that I've misunderstood this a bit, it's changed since I've last used back in August. Now the endpoint is the cloudfront distribution rather the api. So I believe it is doing exactly what I want in the end. I'll mess around with this a bit more before pestering you with more questions.

**Comment by mbklein** [comment]
Yes, the cache is serving a dual purpose here – acting as a general CloudFront cache in front of the API, as well as acting as a “back door” through which to deliver large (> 6MB) responses. There's no actual downside to allowing it to create and configure the caching bucket, unless you're close to the 100-bucket-per-account limit. You won't get charged for anything relating to the bucket unless objects actually get written there. (And whatever _is_ written to it expires after 24 hours, so the cost would be minimal anyway.)

**Comment by mbklein** [comment]
I'm leaving the ticket open since it is an actual bug.

**Comment by mbklein** [comment]
This issue was resolved not by supporting `UseCacheBucket: false` but by _always_ using the >6MB cache bucket when deploying the CloudFront flavor of the app, and _never_ using it when deploying the standalone flavor. (The split is explained in the revised `README`.)
