### ISSUE TITLE
Template uses deprecated Cloudfront fields

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera-labs/serverless-iiif#57]
Hello,

After deploying this with default settings, I noticed that the cloudfront distribution didn't carry over any of the CachingEndpoint settings. I think the way the template is set up uses [deprecated values](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html). I think Cloudfront now requires the use of cache policies for many of these configurations, e.g. MaxTTL and ForwardedValues, etc.

Perhaps relatedly, when accessing an info.json file through the cloudfront endpoint, the file gives the id incorrectly with the api endpoint, which breaks iiif functionality because it's not publicly accessible. Is this because the host is not being properly forwarded?
![image](https://user-images.githubusercontent.com/12830594/144456996-434dadd0-5772-4a60-9f43-707accc7d8c3.png)

**Comment by fitnycdigitalinitiatives** [comment]
Following up on the id in the info.json file, I was able to get that working by adding a custom header for the origin:

X-Forwarded-Host: ....cloudfront.net

Because of the other issues, I'm not sure if it's intended to be done like that or if I'm even doing it exactly right, but it's working.

Best,

Joseph

**Comment by mbklein** [comment]
Ah, yes, the info.json thing was something I encountered a while back, but fixed in the context of using a custom domain name. I guess that didn’t fix it for using the default cloudfront distribution URL. I’ll see what I can do about that, as well as the caching policy issue.
