### ISSUE TITLE
Cross-Origin Request Blocked on info.json files

### ISSUE THREAD

**Issue by mnyrop** [samvera-labs/serverless-iiif#71]
Hi all, 

I just deployed serverless-iiif last week. I used SAM CLI to include the most recent commits after encountering similar permissions issues to #58, and am \*so close!\* to getting an MVP up and running.

Current bug is with CORS. When I try loading my [sample manifest](https://nyu-dss-serverless-iiif-presentation-test.s3.us-east-1.amazonaws.com/rijks-test_kasukawa-001/manifest.json) into my [Mirador instance](https://dss.hosting.nyu.edu/viewpoint/mirador/#manifests[]=https%3A%2F%2Fnyu-dss-serverless-iiif-presentation-test.s3.us-east-1.amazonaws.com%2Frijks-test_kasukawa-001%2Fmanifest.json&theme=dark&thumbs=off&view=single&workspacecontrols=false), i get the following error logged to console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws/latest/iiif/2/rijks-test_kasukawa-001/info.json.  
(Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, https://dss.hosting.nyu.edu/’).
```

But the headers on that resource (https://twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws/latest/iiif/2/rijks-test_kasukawa-001/info.json) via lambda-url show the following:

```sh
➜ curl -I https://twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws/latest/iiif/2/rijks-test_kasukawa-001/info.json
HTTP/1.1 200 OK
Date: Tue, 05 Jul 2022 20:50:28 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
x-amzn-RequestId: f3fb9c92-153a-4454-b767-8f6d583fc09d
access-control-allow-origin: *
X-Amzn-Trace-Id: root=1-62c4a413-7b91ab186defb8460dd48e52;sampled=0
access-control-allow-credentials: true
```

Things I've tried:
- [Enabling CORS on cache bucket](https://docs.sevenbridges.com/docs/enabling-cross-origin-resource-sharing-cors)
- [Forwarding headers from CloudFront](https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/)

Any advice or recommendations? Thanks for your time & repo!

**Comment by mbklein** [comment]
Thanks for reporting this. It looks like a bug in the latest release. I'll check it out.

Details:

It's not that your server isn't returning CORS headers, it's that it's returning _too many_ CORS headers:
```shell
$ curl -v -H 'Origin: https://dss.hosting.nyu.edu' https://twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws/latest/iiif/2/rijks-test_kasukawa-001/info.json

*   Trying 54.204.188.147:443...
* Connected to twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws (54.204.188.147) port 443 (#0)
> GET /latest/iiif/2/rijks-test_kasukawa-001/info.json HTTP/1.1
> Host: twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws
> User-Agent: curl/7.79.1
> Accept: */*
> Origin: https://dss.hosting.nyu.edu
>
< HTTP/1.1 200 OK
< Date: Wed, 06 Jul 2022 03:01:36 GMT
< Content-Type: application/json
< Content-Length: 922
< Connection: keep-alive
< x-amzn-RequestId: b4fe357a-c7cb-4814-bdc6-56b59b59c6a8
< access-control-allow-origin: *
< access-control-allow-origin: https://dss.hosting.nyu.edu
< Vary: Origin
< Access-Control-Expose-Headers: content-type,date,x-amz-server-side-encryption,x-amz-request-id,x-amz-id-2
< X-Amzn-Trace-Id: root=1-62c4fb10-75317dae3901537349cc6ee4;sampled=0
< access-control-allow-credentials: true
< access-control-allow-credentials: true
<
* Connection #0 to host twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws left intact
{"@context":"http://iiif.io/api/image/2/context.json","@id":"https://twt4gwyokx4jxgo2tcptgtn4v40qajbb.lambda-url.us-east-1.on.aws/latest/iiif/2/rijks-test_kasukawa-001","protocol":"http://iiif.io/api/image","width":1686,"height":3000,"sizes":[{"width":1686,"height":3000},{"width":843,"height":1500},{"width":421,"height":750},{"width":210,"height":375},{"width":105,"height":187}],"tiles":[{"width":512,"height":512,"scaleFactors":[1,2,4,8,16]}],"profile":["http://iiif.io/api/image/2/level2.json",{"formats":["jpg","jpeg","tif","tiff","png","webp"],"qualities":["color","gray","bitonal","default"],"supports":["regionByPx","sizeByW","sizeByWhListed","cors","regionSquare","sizeByDistortedWh","sizeAboveFull","canonicalLinkHeader","sizeByConfinedWh","sizeByPct","jsonldMediaType","regionByPct","rotationArbitrary","sizeByH","baseUriRedirect","rotationBy90s","profileLinkHeader","sizeByForcedWh","sizeByWh","mirroring"]}]}%
```

See the doubled-up `access-control-allow-origin` and `access-control-allow-credentials` headers? That's the problem. The error in the JavaScript console (on Safari) shows up as `[Error] Access-Control-Allow-Origin cannot contain more than one origin.`

**Comment by mbklein** [comment]
I think I found the problem – the Lambda Function URL CORS configuration was setting its own values in addition to the ones set in the Lambda function. The newest commit should take care of the problem. You should be able to update your existing stack from the `sam/standalone` directory by running

```
sam build --use-container
```

**Comment by mnyrop** [comment]
That did the trick! Thanks for the fix and for the repo.
