### ISSUE TITLE
Question: is there a recommended approach for securing access to the IIIF resources

### ISSUE THREAD

**Issue by ryantomaselli** [samvera-labs/serverless-iiif#81]
Hey @mbklein :)

The IIIF server is working great...we're deploying the cloudfront option using sam deploy.

Is there a recommended approach to providing security around access to the images. Like say we wanted to do a database look up, verify credentials or check some other business rules before honoring the request.

Do you have insights into that side of things?

All insights appreciated.

**Comment by mbklein** [comment]
Yes, absolutely! Take a look at the [Advanced Usage](https://github.com/samvera-labs/serverless-iiif#advanced-usage) section of the README. What you'd need to do is write and deploy a [Lambda@Edge Function](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html). The function can either alter the incoming request (i.e., add/delete/change headers, query parameters, whatever) or return an HTTP result outright, telling CloudFront to skip calling the Origin and just return what you sent back. A simple auth function would look like this:

```javascript
module.exports = async (event) => {
  const authed = await decideWhetherToAllowAccess(event);

  if (!authed) {
    return {
       statusCode: 403,
       statusDescription: 'Unauthorized'
     };    
  }

  return event;
}
```

The entire HTTP request (along with some other metadata) is available to you in the [`event` object](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html#example-viewer-request).

Once you've deployed that function, you'd configure `serverless-iiif` to use it by adding
```
ViewerRequestARN: [Qualified ARN of the Lambda@Edge Function you just created]
ViewerRequestType: Lambda@Edge
```

You'll also see references to [CloudFront Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html), but those can't have dependencies or network access, so their functionality is far more limited. If you want to auth via a DB lookup or an API call, you'll need to use Lambda@Edge.

**Comment by ryantomaselli** [comment]
Super appreciate the detailed response, this is great.

Thanks @mbklein

**Comment by ryantomaselli** [comment]
One thing I noticed is that the deploy fails if I don't provide the version for the Viewer Request Lambda (as in qualify the arn with version number.

To get past this I had publish a new version and then reference the version qualified arn.

```
`Resource handler returned message: "Invalid request provided: The function ARN must reference a specific function version. (The ARN must end with the version number.) ARN: arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:function:CheckAuthIIIFImageRequest-xxxxxxxxxxx (Service: CloudFront, Status Code: 400, Request ID: xxxxxxxxxxx)"
`
```

**Comment by ryantomaselli** [comment]
> One thing I noticed is that the deploy fails if I don't provide the version for the Viewer Request Lambda (as in qualify the arn with version number.
> 
> To get past this I had publish a new version and then reference the version qualified arn.
> 
> ```
> Resource handler returned message: "Invalid request provided: The function ARN must reference a specific function version. (The ARN must end with the version number.) ARN: arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:function:CheckAuthIIIFImageRequest-xxxxxxxxxxx (Service: CloudFront, Status Code: 400, Request ID: xxxxxxxxxxx)
> ```

Ah, I see

**Comment by fitnycdigitalinitiatives** [comment]
It doesn't have good documentation but you can take a look at our authentication function that we based off what Michael did at Northwestern: https://github.com/fitnycdigitalinitiatives/iiif-authenticate

Basically, we have a DynamoDB listing every image key and whether it's public or private, and when a request comes in it checks whether it's a public image to let it through, if not, it checks for the presence of a valid JWT that would only be sent if someone is logged into our repository system. It's very simple.

**Comment by ryantomaselli** [comment]
I really appreciate both you guys sharing all this...it's really made my Friday

**Comment by ryantomaselli** [comment]
Hey guys, would you create a Serverless Framework service for a standalone Lambda edge function or just a SAM application? For my primary API I use Serverless Framework.

I didn't want it as part of my primary API because the bundle size has to be small (1MB). I could create it as a micro service to the primary API. That said the IIIF Server is deployed with SAM so perhaps sticking to that is better. 

An advantage to using Serverless Framework in my mind is that the Primary API uses it so would be more familiar to devs on the project.

**Comment by ryantomaselli** [comment]
Hey guys;

So I'm using Serverless Framework to generate the lamba but if I want to do a dynamodb look up using even the module only import - @aws-sdk/client-dynamodb-node - this blows up the compressed size of my lambda function to over 2 megs, way over the 1MB limit.

@fitnycdigitalinitiatives I noticed your authenticate function imports the entire AWS SDK (aws-sdk). Are you using the Origin request event by chance (which has a bigger limit of 50 MB). I'm using the Viewer request as it seemed the most appropriate for validating the request (auth tokens and business rule check with dynamodb look up).
