### ISSUE TITLE
Customizing Support for Different Image Formats

### ISSUE THREAD

**Issue by codeclout** [samvera-labs/serverless-iiif#83]
Hi,

Is there any information we should be made aware of, outside of the custom `libvips` and minor tweaks to the `standalone` CF template, that can help in achieving the goal of supporting JPEG 2000 formatted images?

**Comment by mbklein** [comment]
Not that I know of. The only thing blocking support is being able to build a JPEG 2000-enabled `libvips` and linking `sharp` against it. I've taken a run at it a few times, but since we don't use JP2 in house, I didn't put a lot of time into it. I might take another shot in a few weeks.

**Comment by orangewolf** [comment]
we are interested in this too and do have a libvips build script for another lambda. I'll see if I can start a PR for this.

**Comment by codeclout** [comment]
@orangewolf - Thank you for tackling this. After multiple attempts to resolve, the following error is the current blocker. 

```json
{
  "errorType": "Error",
    "errorMessage": "\nSomething went wrong installing the \"sharp\" module\n\nlibvips-cpp.so.42: cannot open shared object file: No such file or directory\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
}
```

I am thinking this can be resolved by building and running this process in a Docker container and using Lambda to run the container. I have not yet attempted this approach, but more interested in your thoughts on this being a viable solution.

Thanks,
Brian

**Comment by orangewolf** [comment]
@codeclout in the draft PR above, we build a layer to handle the updated Sharp. You don't really want to run docker in your lambda because spin up time becomes killer. There are instructions here: https://github.com/samvera-labs/serverless-iiif/pull/86/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L106 for trying it out. Michael is planning to publish the layer, which will negate the need to build it locally.

**Comment by codeclout** [comment]
@orangewolf  - thank you

**Comment by codeclout** [comment]
@orangewolf - Thanks again for the new layer... I just had time allocated to spin it up this sprint. I'm getting the following error. 
```json
"errorMessage": "\nSomething went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp-linux-x64.node'\nRequire stack:\n- /var/task/node_modules/sharp/lib/sharp.js\n- /var/task/node_modules/sharp/lib/constructor.js\n- /var/task/node_modules/sharp/lib/index.js\n- /var/task/node_modules/iiif-processor/lib/transform.js\n- /var/task/node_modules/iiif-processor/index.js\n- /var/task/index.js\n- /var/runtime/index.mjs\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
```
Any thoughts as to what we're doing incorrectly? 

Thanks in advance
